version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./TelerikAcademy.TripyMate/TelerikAcademy.TripyMate.sln
build:
  project: ./TelerikAcademy.TripyMate/TelerikAcademy.TripyMate.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
