// <auto-generated />
namespace TelerikAcademy.TripyMate.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newmode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmode));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141049073_new mode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
